### ISSUE TITLE
List of Suggestions for Improvement

### ISSUE THREAD

**Issue by Avinkav** [luckyseven/ngx-liquid-cache#1]
- **Allow users to set cache prefix** - While localStorage is unique per domain, the same domain may serve multiple different Angular apps. By allowing users to select their own cache prefix, conflicts can be avoided.
- **Perform local storage lookup on `get()`** - This will allow the cache to stay in sync across tabs/windows.
- **Perform local storage lookup on `has()`** - Same as above. Maintain a consistent cache across tabs/windows

- **Fire side-effects on tap** - Improved readability.
```
map(results => {
  DecoratorLiquidCacheService.cacheService.set(parsedKey, results, configuration);
  return results;
}
tap(results => DecoratorLiquidCacheService.cacheService.set(parsedKey, results, configuration))
```

**Comment by luckyseven** [comment]
Very interesting suggestions, thanks! I'll integrate them soon.

**Comment by luckyseven** [comment]
Thanks again for your support. Please try the updated library and let me know if you find issues ;)
